version: '3.4'

services:
    musify-grpc-env:
        build:
            context: .
            dockerfile: ./Dockerfile
        expose:
            - "8888"
        ports:
            - "0.0.0.0:8888:8888"
        volumes:
            - ./Musify:/Musify/Musify
        network_mode: musify_network
