version: '3.4'

services:
    musify-grpc-env:
        build:
            context: .
            dockerfile: ./Dockerfile
        expose:
            - "8888"
        ports:
            - "0.0.0.0:8888:8888"
        volumes:
            - ./Musify:/Musify/Musify
        networks:
            musify_network: # Requiere ejecutarse docker network create --driver bridge --subnet 172.250.6.0/24 musify_network
                ipv4_address: 172.250.6.3

networks:
    musify_network:
        external: true

