# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: musify_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='musify_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14musify_service.proto\")\n\tSongChunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\"*\n\nSongStored\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06length\x18\x02 \x01(\x05\",\n\x0bSongRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07quality\x18\x02 \x01(\t2`\n\rMusifyService\x12%\n\x06upload\x12\n.SongChunk\x1a\x0b.SongStored\"\x00(\x01\x12(\n\x08\x64ownload\x12\x0c.SongRequest\x1a\n.SongChunk\"\x00\x30\x01\x62\x06proto3'
)




_SONGCHUNK = _descriptor.Descriptor(
  name='SongChunk',
  full_name='SongChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='SongChunk.buffer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='SongChunk.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=65,
)


_SONGSTORED = _descriptor.Descriptor(
  name='SongStored',
  full_name='SongStored',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SongStored.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='SongStored.length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=109,
)


_SONGREQUEST = _descriptor.Descriptor(
  name='SongRequest',
  full_name='SongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SongRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quality', full_name='SongRequest.quality', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['SongChunk'] = _SONGCHUNK
DESCRIPTOR.message_types_by_name['SongStored'] = _SONGSTORED
DESCRIPTOR.message_types_by_name['SongRequest'] = _SONGREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SongChunk = _reflection.GeneratedProtocolMessageType('SongChunk', (_message.Message,), {
  'DESCRIPTOR' : _SONGCHUNK,
  '__module__' : 'musify_service_pb2'
  # @@protoc_insertion_point(class_scope:SongChunk)
  })
_sym_db.RegisterMessage(SongChunk)

SongStored = _reflection.GeneratedProtocolMessageType('SongStored', (_message.Message,), {
  'DESCRIPTOR' : _SONGSTORED,
  '__module__' : 'musify_service_pb2'
  # @@protoc_insertion_point(class_scope:SongStored)
  })
_sym_db.RegisterMessage(SongStored)

SongRequest = _reflection.GeneratedProtocolMessageType('SongRequest', (_message.Message,), {
  'DESCRIPTOR' : _SONGREQUEST,
  '__module__' : 'musify_service_pb2'
  # @@protoc_insertion_point(class_scope:SongRequest)
  })
_sym_db.RegisterMessage(SongRequest)



_MUSIFYSERVICE = _descriptor.ServiceDescriptor(
  name='MusifyService',
  full_name='MusifyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=157,
  serialized_end=253,
  methods=[
  _descriptor.MethodDescriptor(
    name='upload',
    full_name='MusifyService.upload',
    index=0,
    containing_service=None,
    input_type=_SONGCHUNK,
    output_type=_SONGSTORED,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='download',
    full_name='MusifyService.download',
    index=1,
    containing_service=None,
    input_type=_SONGREQUEST,
    output_type=_SONGCHUNK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MUSIFYSERVICE)

DESCRIPTOR.services_by_name['MusifyService'] = _MUSIFYSERVICE

# @@protoc_insertion_point(module_scope)
